CREATE DATABASE FERRETERIA;
USE FERRETERIA;

CREATE TABLE EMPRESA(
  IDEmpresa INT AUTO_INCREMENT NOT NULL,
  Nombre VARCHAR(100) NOT NULL,
  NIT CHAR(17) NOT NULL,
  NumeroContribuyente INT NOT NULL,
  Email VARCHAR(100),
  Telefono CHAR(8),
  UNIQUE(IDEmpresa),
  UNIQUE(NIT),
  UNIQUE(NumeroContribuyente),
  UNIQUE(Email),
  UNIQUE(Telefono)
);

CREATE TABLE PROVEEDOR(
  IDProveedor INT AUTO_INCREMENT NOT NULL,
  Nombre VARCHAR(100) NOT NULL,
  DUI CHAR(10) NOT NULL,
  NIT CHAR(17) NOT NULL,
  Email VARCHAR(100),
  Telefono CHAR(8),
  IDEmpresa INT NOT NULL,
  UNIQUE(IDProveedor),
  UNIQUE(DUI),
  UNIQUE(NIT),
  UNIQUE(Email),
  UNIQUE (Telefono)
);


