CREATE DATABASE FERRETERIA;
USE FERRETERIA;

CREATE TABLE EMPRESA(
  IDEmpresa INT AUTO_INCREMENT NOT NULL,
  NombreEmpresa VARCHAR(100) NOT NULL,
  NIT CHAR(17) NOT NULL,
  NumeroContribuyente INT NOT NULL,
  Email VARCHAR(100) NULL,
  Telefono CHAR(8) NOT NULL,
  UNIQUE(IDEmpresa),
  UNIQUE(NIT),
  UNIQUE(NumeroContribuyente),
  UNIQUE(Email),
  UNIQUE(Telefono)
);

CREATE TABLE PROVEEDOR(
  IDProveedor INT AUTO_INCREMENT NOT NULL,
  NombreProveedor VARCHAR(100) NOT NULL,
  DUI CHAR(10) NOT NULL,
  NIT CHAR(17) NOT NULL,
  Email VARCHAR(100) NULL,
  Telefono CHAR(8) NULL,
  IDEmpresa INT NOT NULL,
  UNIQUE(IDProveedor),
  UNIQUE(DUI),
  UNIQUE(NIT),
  UNIQUE(Email),
  UNIQUE (Telefono)
);

CREATE TABLE PRODUCTO(
  IDProducto INT AUTO_INCREMENT NOT NULL,
  NombreProducto VARCHAR(100) NOT NULL,
  Costo FLOAT(15,2) DEFAULT (0) NOT NULL,
  Precio FLOAT(15, 2) DEFAULT (0) NOT NULL,
  FechaCaducidad DATE NULL,
  IDMarca INT NOT NULL,
  IDTipo INT NOT NULL,
  UNIQUE(IDProducto)
);

CREATE TABLE TIPO(
  IDTipo INT AUTO_INCREMENT NOT NULL,
  Tipo VARCHAR(50) NULL,
  IDSubArea INT NOT NULL,
  UNIQUE(IDTipo)
);

CREATE TABLE SUBAREA(
  IDSubArea INT AUTO_INCREMENT NOT NULL,
  SubArea VARCHAR(50) NULL,
  IDArea INT NOT NULL,
  UNIQUE(IDSubArea)
);

CREATE TABLE AREA(
  IDArea INT AUTO_INCREMENT NOT NULL,
  Area VARCHAR(50),
  UNIQUE(IDArea)
);

CREATE TABLE PROVEEDORXPRODUCTOXUSUARIO(
  IDProveedor INT NOT NULL,
  IDProducto INT NOT NULL,
  IDUsuario INT NOT NULL,
  Cantidad INT DEFAULT(0),
  Precio DECIMAL(15, 2) DEFAULT(0) NOT NULL,
  FechaIngreso DATE NOT NULL
);

CREATE TABLE ITEM(
  IDItem INT AUTO_INCREMENT NOT NULL,
  NombreItem VARCHAR(100) NULL,
  Descripcion VARCHAR(500) NULL,
  Costo FLOAT(15,2) DEFAULT (0) NOT NULL,
  Precio FLOAT(15, 2) DEFAULT (0) NOT NULL,
  Medidas VARCHAR(50),
  IDProducto INT,
  UNIQUE(IDItem)
);

CREATE TABLE MARCA(
  IDMarca INT AUTO_INCREMENT NOT NULL,
  NombreMarca VARCHAR(100),
  UNIQUE(IDMarca)
);

CREATE TABLE SUCURSAL(
  IDSucursal INT AUTO_INCREMENT NOT NULL,
  Direccion VARCHAR(200),
  Telefono CHAR(8),
  UNIQUE (IDSucursal)
);


#Declaraciones de llaves primarias
ALTER TABLE EMPRESA ADD CONSTRAINT PK_Empresa PRIMARY KEY (IDEmpresa);
ALTER TABLE PROVEEDOR ADD CONSTRAINT PK_Proveedor PRIMARY KEY (IDProveedor);
ALTER TABLE PRODUCTO ADD CONSTRAINT PK_Producto PRIMARY KEY (IDProducto);
ALTER TABLE TIPO ADD CONSTRAINT PK_TIPO PRIMARY KEY (IDTipo);
ALTER TABLE SUBAREA ADD CONSTRAINT PK_SUBAREA PRIMARY KEY (IDSubArea);
ALTER TABLE AREA ADD CONSTRAINT PK_AREA PRIMARY KEY (IDArea);
ALTER TABLE PROVEEDORXPRODUCTOXUSUARIO ADD CONSTRAINT PK_PXPXU PRIMARY KEY (IDProducto, IDProveedor, IDUsuario); #PXPXU = PROVEEDORXPRODUCTOXUSUARIO
ALTER TABLE ITEM ADD CONSTRAINT PK_ITEM PRIMARY KEY (IDItem);
ALTER TABLE MARCA ADD CONSTRAINT PK_MARCA PRIMARY KEY (IDMarca);
ALTER TABLE SUCURSAL ADD CONSTRAINT PK_SUCURSAL PRIMARY KEY (IDSucursal);